// gencli writes docs/cli.md from `siphon help --json` on stdin, so the CLI
// reference can't drift from the command table (go generate ./docs).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

type flag struct{ Name, Type, Default, Description string }

type command struct {
	Name, Summary, Usage, Mode, Example string
	Flags                               []flag
}

type help struct {
	Version     string
	Commands    []command
	GlobalFlags []flag            `json:"global_flags"`
	ExitCodes   map[string]string `json:"exit_codes"`
	Kinds       []string
}

func main() {
	var h help
	if err := json.NewDecoder(os.Stdin).Decode(&h); err != nil {
		fmt.Fprintln(os.Stderr, "gencli:", err)
		os.Exit(1)
	}
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }
	w("# CLI reference\n\n")
	w("<!-- Generated by `go generate ./docs` from `siphon help --json`. Do not edit by hand. -->\n\n")
	w("`siphon` has two modes:\n\n")
	w("- **Client mode** talks to a running Siphon over its API, from any machine.\n")
	w("  Log in once with `siphon login <url>`, or set `SIPHON_URL` and\n")
	w("  `SIPHON_TOKEN_FILE`.\n")
	w("- **Local mode** works on the config file and the database directly\n")
	w("  (`serve`, `validate`, …). Any command given `-config` is local.\n\n")
	w("An AI assistant can read all of this as JSON: `siphon help --json`. It\n")
	w("should also read `siphon guide`.\n\n")
	w("## Flags for every client command\n\n| Flag | Default | Meaning |\n|---|---|---|\n")
	for _, f := range h.GlobalFlags {
		w("| `%s` | %s | %s |\n", dash(f.Name), dflt(f.Default), f.Description)
	}
	w("\nKinds for `get`: %s.\n\n", "`"+strings.Join(h.Kinds, "`, `")+"`")
	w("## Exit codes\n\n| Code | Meaning |\n|---|---|\n")
	codes := make([]string, 0, len(h.ExitCodes))
	for c := range h.ExitCodes {
		codes = append(codes, c)
	}
	sort.Strings(codes)
	for _, c := range codes {
		w("| %s | %s |\n", c, h.ExitCodes[c])
	}
	w("\nWith `-o json`, errors on stderr are `{\"error\": \"…\", \"errors\": […], \"hint\": \"…\"}`.\n")
	for _, mode := range []string{"client", "local"} {
		w("\n## %s commands\n", map[string]string{"client": "Client", "local": "Local"}[mode])
		for _, c := range h.Commands {
			if c.Mode != mode {
				continue
			}
			w("\n### siphon %s\n\n%s.\n\n```sh\n%s\n```\n", c.Name, capitalise(c.Summary), c.Usage)
			if len(c.Flags) > 0 {
				w("\n| Flag | Default | Meaning |\n|---|---|---|\n")
				for _, f := range c.Flags {
					w("| `%s` | %s | %s |\n", dash(f.Name), dflt(f.Default), f.Description)
				}
			}
			if c.Example != "" {
				w("\nExample:\n\n```sh\n%s\n```\n", c.Example)
			}
		}
	}
	os.Stdout.WriteString(b.String())
}

// dash writes -o for one-letter flags and --name for the rest.
func dash(n string) string {
	if len(n) == 1 {
		return "-" + n
	}
	return "--" + n
}

func dflt(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func capitalise(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
