// gencatalog writes docs/connections/README.md from the service catalogue
// (internal/catalog/services.yaml), so the list of services can't drift
// (go generate ./docs).
package main

import (
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/olafkfreund/siphon/docs"
	"github.com/olafkfreund/siphon/internal/catalog"
)

var categories = []struct{ id, title string }{
	{"code", "Code hosting"}, {"issues", "Issue tracking"}, {"chat", "Chat"},
	{"monitoring", "Monitoring & alerting"}, {"cloud", "Cloud"}, {"payments", "Payments"},
	{"home", "Home & IoT"}, {"generic", "Generic"},
}

// pages are the hand-written connection pages with more to say.
var pages = map[string]string{"github": "github.md", "gitlab": "gitlab.md", "aws": "aws.md"}

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }
	w("# Services you can connect\n\n")
	w("<!-- Generated by `go generate ./docs` from internal/catalog/services.yaml. Do not edit by hand. -->\n\n")
	w("Connect a service from the CLI or the portal's **Services** page. It creates the right\n")
	w("sources (agent tools, polling, webhooks), stores tokens write-only, shows a webhook\n")
	w("secret once, and tests the connection:\n\n")
	w("```sh\nsiphon catalog                     # what you can connect on this install\nsiphon connect linear --token @linear.key --webhook\n```\n\n")
	w("**Available** works now. **Needs package** works once the operator installs the pinned\n")
	w("MCP server (`services.siphon.catalogPackages`); its webhooks work either way. **Not yet**\n")
	w("lists what's missing. Models and subscription logins are on their own pages:\n")
	w("[models](models.md), [logins](logins.md).\n")
	tpls := docs.Templates()
	for _, c := range categories {
		var rows []*catalog.Entry
		for _, e := range catalog.All() {
			if e.Category == c.id {
				rows = append(rows, e)
			}
		}
		if len(rows) == 0 {
			continue
		}
		w("\n## %s\n\n| Service | Gives agents | Status | Connect | Templates |\n|---|---|---|---|---|\n", c.title)
		for _, e := range rows {
			name := e.Name
			if p, ok := pages[e.ID]; ok {
				name = fmt.Sprintf("[%s](%s)", e.Name, p)
			}
			status, connect := "available", fmt.Sprintf("`siphon connect %s`", e.ID)
			switch {
			case e.Status == "not-yet":
				status, connect = "not yet: "+e.Reason, "—"
			case e.Nix != nil:
				status = fmt.Sprintf("needs package for tools (`catalogPackages = [ \"%s\" ]`)", e.ID)
			case len(e.NeedsPackage) > 0:
				status = "needs package: " + e.Reason
			}
			var used []string
			for _, t := range tpls {
				if slices.ContainsFunc(t.Needs, func(n string) bool {
					return n == "sources/"+e.ID || strings.HasPrefix(n, "sources/"+e.ID+"-")
				}) {
					used = append(used, fmt.Sprintf("[`%s`](../templates/%s.yaml)", t.Name, t.Name))
				}
			}
			w("| %s | %s | %s | %s | %s |\n", name, strings.Join(e.Capabilities, ", "), status, connect, strings.Join(used, " "))
		}
	}
	os.Stdout.WriteString(b.String())
}
