// genllms writes llms-full.txt: every guide page and template in reading
// order, so an assistant can load the whole guide in one fetch
// (go generate ./docs; run from the docs directory).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// order is the reading order; pages not listed follow, alphabetically.
var order = []string{
	"README.md", "getting-started.md", "concepts.md", "llm.md",
	"tasks/webhook-command.md", "tasks/poll-threshold.md", "tasks/github-pr-agent.md",
	"tasks/mcp-watch.md", "tasks/routine.md", "tasks/approvals.md",
	"connections/models.md", "connections/logins.md", "connections/github.md",
	"connections/gitlab.md", "connections/aws.md",
	"troubleshooting.md", "drafting.md", "cli.md", "templates/README.md",
}

func main() {
	seen := map[string]bool{}
	var pages []string
	for _, p := range order {
		if _, err := os.Stat(p); err == nil {
			pages, seen[p] = append(pages, p), true
		}
	}
	var rest []string
	for _, pat := range []string{"*.md", "tasks/*.md", "connections/*.md"} {
		m, _ := filepath.Glob(pat)
		for _, p := range m {
			if !seen[p] {
				rest = append(rest, p)
			}
		}
	}
	sort.Strings(rest)
	pages = append(pages, rest...)
	tpls, _ := filepath.Glob("templates/*.yaml")
	sort.Strings(tpls)

	var b strings.Builder
	b.WriteString("# Siphon: the full user guide and templates\n\n")
	b.WriteString("> Generated by `go generate ./docs`. The index is llms.txt; the source is docs/ in https://github.com/olafkfreund/siphon.\n")
	for _, p := range append(pages, tpls...) {
		data, err := os.ReadFile(p)
		if err != nil {
			fmt.Fprintln(os.Stderr, "genllms:", err)
			os.Exit(1)
		}
		fmt.Fprintf(&b, "\n\n---\n\n<!-- file: docs/%s -->\n\n", p)
		if strings.HasSuffix(p, ".yaml") {
			fmt.Fprintf(&b, "```yaml\n%s```\n", data)
		} else {
			b.Write(data)
		}
	}
	os.Stdout.WriteString(b.String())
}
